name: Build F1 Telemetry App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore ./F1TelemetryApp/F1TelemetryApp.sln
 
    - name: Build App
      run: msbuild F1TelemetryApp/F1TelemetryApp.sln /p:Configuration=Release
      
    - name: Run NUnit Tests
      run: ./F1TelemetryApp/packages/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe .F1TelemetryApp/bin/Release/F1TelemetryAppTests.dll