name: Build F1 Telemetry App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
        working-drectory: ./F1TelemetryApp

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore ./F1TelemetryApp.sln
      working-directory: ${{env.working-directory}}
 
    - name: Build App
      run: msbuild ./F1TelemetryApp.sln /p:Configuration=Release
      working-directory: ${{env.working-directory}}
      
    - name: Run NUnit Tests
      run: ./packages/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./bin/Release/F1TelemetryAppTests.dll
      working-directory: ${{env.working-directory}}